In [2]:
import numpy as np
import random

def possible_direction(row,column):
    direction = ['N','E','S','W']
    if (row == 0):
        direction.remove('N')
    if (row == len(R)-1):
        direction.remove('S')
    if (column == 0):
        direction.remove('W')
    if (column == len(R)-1):
        direction.remove('E')
    return direction

def nextState(row,column, direction):
    if(direction == 'N'):
        row = row -1
    if(direction == 'E'):
        column = column + 1
    if(direction == 'S'):
        row = row + 1
    if(direction == 'W'):
        column = column -1
    return [row,column]

def possible_action_Q(Q,qRow,qColumn,direction):
    valueNextAction = []
    for d in direction:
        [nRow,nColumn] = nextState(qRow,qColumn,d)
        valueNextAction.append([d,Q[nRow,nColumn]])
    return valueNextAction
    
##=========== Learning
# Setting Gamma
Gamma = 0.9
# Initialize matrix R
R = np.loadtxt('Data Tugas 3 RL.txt')
# Initialize matrix Q to zero
Q = np.zeros((10,10), dtype=int)

for episode in range(1,1001):
    # initial state
    [row,column] = [9,0]
    current_state = R[row,column]    
    
    while current_state != 100:
        # selecting one of possible direction
        direction = random.choice(possible_direction(row,column))
        [nextRow,nextColumn] = nextState(row,column,direction)
        
        # get possible action from next state
        valueNextAction = possible_action_Q(Q,nextRow,nextColumn,possible_direction(nextRow,nextColumn))
        
        # get maximum Q value for next state and insert to Q next state
        Q[nextRow,nextColumn] = R[nextRow,nextColumn] + (Gamma * max(valueNextAction, key=lambda x:x[1])[1])
        
        # set next state as the current state
        [row,column] = [nextRow,nextColumn]
        current_state = R[row,column] 
    
##=========== Running
# initial state
[row,column] = [9,0]
direction = []
current_state = R[row,column]   
Totalscore = Q[row,column]
ListReward = [current_state]

while current_state != 100:
    # get possible action direction
    direction = possible_direction(row,column)
    listNextAction = possible_action_Q(Q,row,column,direction) 
    
    # get best direction
    bestDirection = max(listNextAction, key=lambda x:x[1])[0]
    
    # set next state as the current state
    [nextRow,nextColumn] = nextState(row,column,bestDirection)
    [row,column] = [nextRow,nextColumn]
    current_state = R[row,column] 
    Totalscore = Totalscore + Q[row,column]
    ListReward.append(current_state)
    
print('========================================')
print('Reward = ', sum(ListReward))
print('Number of Action = ', len(ListReward)-1)
print('Total Score = ', Totalscore)
print('========================================')


Reward =  60.0
Number of Action =  18
Total Score =  4165


In [3]:
print(Q)

[[179 200 226 257 287 323 363 409 461 514]
 [160 181 203 227 256 285 323 363 409 457]
 [141 158 178 203 227 252 286 324 365 406]
 [123 137 158 177 203 226 256 291 325 361]
 [108 125 143 163 184 206 230 257 289 320]
 [ 95 110 124 144 161 180 206 230 258 284]
 [ 82  96 111 126 143 159 181 204 231 252]
 [ 71  84  94 110 127 139 157 179 205 222]
 [ 66  76  86  97 113 122 139 161 180 198]
 [ 54  65  76  85  97 106 122 142 160 176]]


In [4]:
print(R)

[[  -1.   -3.   -5.   -1.   -3.   -3.   -5.   -5.   -1.  100.]
 [  -2.   -1.   -1.   -4.   -2.   -5.   -3.   -5.   -5.   -5.]
 [  -3.   -4.   -4.   -1.   -3.   -5.   -5.   -4.   -3.   -5.]
 [  -3.   -5.   -2.   -5.   -1.   -4.   -5.   -1.   -3.   -4.]
 [  -4.   -3.   -3.   -2.   -1.   -1.   -1.   -4.   -3.   -4.]
 [  -4.   -2.   -5.   -2.   -4.   -5.   -1.   -2.   -2.   -4.]
 [  -4.   -3.   -2.   -3.   -1.   -3.   -4.   -3.   -1.   -3.]
 [  -4.   -2.   -5.   -4.   -1.   -4.   -5.   -5.   -2.   -4.]
 [  -2.   -1.   -1.   -4.   -1.   -3.   -5.   -1.   -4.   -1.]
 [  -5.   -3.   -1.   -2.   -4.   -3.   -5.   -2.   -2.   -2.]]


In [6]:
print(np.array(ListReward))

[  -5.   -2.   -1.   -1.   -4.   -1.   -1.   -1.   -4.   -1.   -1.   -1.
   -4.   -1.   -3.   -3.   -5.   -1.  100.]
